services:
  # Frontend - Static Site
  - type: web
    name: prithwis-portfolio-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend - Web Service for API
  - type: web
    name: prithwis-portfolio-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BREVO_API_KEY
        fromService: prithwis-portfolio-backend
        fromEnvVar: BREVO_API_KEY
      - key: SENDER_EMAIL
        value: daasprithwis864@gmail.com
      - key: RECIPIENT_EMAIL
        value: daasprithwis864@gmail.com