services:
  # Backend - Web Service for API
  - type: web
    name: prithwis-portfolio-backend
    env: node
    region: oregon
    plan: free
    rootDir: ./backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BREVO_API_KEY
        sync: false
      - key: SENDER_EMAIL
        value: daasprithwis864@gmail.com
      - key: RECIPIENT_EMAIL
        value: daasprithwis864@gmail.com

  # Frontend - Static Site
  - type: web
    name: prithwis-portfolio-frontend
    env: static
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html